server:
  port: 8042
logging:
  level:
    root: INFO
#    de.ume: INFO
    de.ume: DEBUG
  file.name: ./logs/application-debug.log

aop:
  method-logging: false

projects:
  "test-project1":
    use-virtual-threads: true # default value: false,
                               # if set to true, parallelism can be set for data-selection, pseudonymization, data-storing separately
    parallelism: 16 # is used only, if use-virtual-threads is set to false
#    lastUpdated:
#      zone-id: "UTC"
#      hashmap:
#        domain: test-project
#      gpas:
#        domain: test-project
#        gpasServiceWsdlUrl: http://localhost:8081/gpas/gpasService?wsdl
#        domainServiceWsdlUrl: http://localhost:8081/gpas/DomainService?wsdl
    cohort-selection:
      via-ids:
        ids: ["1234-identifier", "234-identifier"]
#      via-plugin:
#        implementation: plugin-impl
#        config:
#          url: profile-url

#      via-file:
#        path: ./path/to/file
#        delimiter: ","          # delimiter regex expression, leading and trailing white spaces are removed

#      via-csv:
#        path: ./path/to/file
#        delimiter: ";"          # delimiter regex expression, leading and trailing white spaces are removed
#        column-name: "Aufnahme-Nr."
#        column-number: 3       # if set, column-name is ignored
#        skip-first-row: true  # default: false, only applicable if column-number is set

#      firemetrics:
#        host: &firemetrics-host <insert-host-here>
#        port: &firemetrics-port <insert-port-here>
#        database: &firemetrics-database <insert-database-here>
#        user: &firemetrics-user <insert-user-here>
#        password: &firemetrics-password <insert-password-here>
#        # config file with sql statements
#        # configFile: ./path/to/file
#        # or sql query
#        query: |
#          select b0.id
#          from biologicallyderivedproduct b0
#          order by b0.id asc
#          limit 1000 offset 0

    data-selection:
      parallelism: 10 # Can be set to limit the number of parallel connections
#      fhir-collector:
#        configurationFile: ./src/main/resources/fhir-collector.yaml
      fhir-server:
        url: http://localhost:8082/fhir
#        basic-auth:
#          user: <insert-user-here>
#          password: <insert-password-here>
#        token-auth:
#          token: <insert-token-here>
        fhirIdQueryPlaceholder: <id>
        fhirIdQuery: Patient?identifier=<id>
        bundleQueryLastUpdatedPlaceholder: <lastUpdated>
        bundleQueryPlaceholder: <fhir-id>
        bundleQuery: Patient/<fhir-id>/$everything?_count=100000
#        bundleQuery: Patient?_id=<fhir-id>&_lastUpdated=ge<lastUpdated>

    pseudonymization:
      parallelism: 10 # Can be set to limit the number of parallel connections
#      none: # for no pseudonymization
      deidentifhir:
        scraperConfigFile: ./deidentifhir/mii/deidentiFHIR_IDScraper.profile
        pseudonymizationConfigFile: ./deidentifhir/mii/deidentiFHIR_CDtoTransport.profile
        generateIDScraperConfig: false
        dateShiftingInMillis: 2419200000
        hashmap:
          domain: test-project
#        gpas:
#          domain: test-project
#          gpasServiceWsdlUrl: http://localhost:8081/gpas/gpasService?wsdl
#          domainServiceWsdlUrl: http://localhost:8081/gpas/DomainService?wsdl
    data-storing:
      parallelism: 10 # Can be set to limit the number of parallel connections
#      folder:
#        path: /bla/
      fhir-server:
        url: http://localhost:8083/fhir
#        basic-auth:
#          user: <insert-user-here>
#          password: <insert-password-here>
#        token-auth:
#          token: <insert-token-here>

  "test-project2":
    cohort-selection:
      gics:
        main-wsdl-uri: http://localhost:8080/gics/gicsService?wsdl
        domain: MII
        policies: [ "IDAT_erheben", "IDAT_speichern_verarbeiten", "MDAT_erheben", "MDAT_speichern_verarbeiten" ]
    data-selection:
      fhir-server:
        url: http://localhost:8082/fhir
        fhirIdQueryPlaceholder: <id>
        fhirIdQuery: Patient?identifier=<id>
        bundleQueryPlaceholder: <fhir-id>
        bundleQuery: Patient/<fhir-id>/$everything?_count=100000
    pseudonymization:
      deidentifhir:
        scraperConfigFile: ./deidentifhir/mii/deidentiFHIR_IDScraper.profile
        pseudonymizationConfigFile: ./deidentifhir/mii/deidentiFHIR_CDtoTransport.profile
        generateIDScraperConfig: false
        dateShiftingInMillis: 2419200000
        gpas:
          domain: test-project
          gpasServiceWsdlUrl: http://localhost:8081/gpas/gpasService?wsdl
          domainServiceWsdlUrl: http://localhost:8081/gpas/DomainService?wsdl
    data-storing:
      fhir-server:
        url: http://localhost:8083/fhir
