name: Build and test

on:
  push

jobs:
  check-code-style:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'maven'

      - name: Check code style
        run:
          mvn spotless:check --batch-mode --no-transfer-progress --file $GITHUB_WORKSPACE/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'maven'
      - uses: gacts/install-hurl@v1
      - name: Build jar
        run:
          mvn -U clean package --batch-mode --no-transfer-progress --file $GITHUB_WORKSPACE/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}

      - name: Integrationtests
        run: cd integrationtests && ./start-integrationtests.sh

  deploy-jar:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'maven'
      - name: Deploy jar
        run:
          mvn -U clean deploy --batch-mode --no-transfer-progress --file $GITHUB_WORKSPACE/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
