name: Build and test

on:
  push:
    branches:
      - '**'
  release:
    types:
      - created

jobs:
  check-code-style:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Check code style
        run:
          mvn spotless:check --batch-mode --no-transfer-progress --file $GITHUB_WORKSPACE/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'
      - uses: gacts/install-hurl@v1
      - name: Build jar
        run:
          mvn -U clean package --batch-mode --no-transfer-progress --file $GITHUB_WORKSPACE/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Integrationtests
        run: cd integrationtests && ./start-integrationtests.sh

  publish-jar-and-image:
    needs: build-and-test
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'
      - name: Deploy jar
        run:
          mvn -U clean deploy --batch-mode --no-transfer-progress --file $GITHUB_WORKSPACE/pom.xml -Djar.version=${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        run: |
          DOCKER_BUILDKIT=1 docker build -t deidentifhir-pipeline:${{ github.event.release.tag_name }} -t deidentifhir-pipeline:latest --build-arg deidentifhir_pipeline_version=${{ github.event.release.tag_name }} .
          docker tag deidentifhir-pipeline:${{ github.event.release.tag_name }} ghcr.io/umessen/deidentifhir-pipeline:${{ github.event.release.tag_name }}
          docker tag deidentifhir-pipeline:latest ghcr.io/umessen/deidentifhir-pipeline:latest
          docker push ghcr.io/umessen/deidentifhir-pipeline:${{ github.event.release.tag_name }}
          docker push ghcr.io/umessen/deidentifhir-pipeline:latest
